export const SET_SONG_LIST = 'SET_SONG_LIST'

export const SET_PLAYING_SONG = 'SET_PLAYING_SONG'

export const SET_HISTORY_SONG_LIST = 'SET_HISTORY_SONG_LIST'

export const SET_RADIO_STATION_SONG = 'SET_RADIO_STATION_SONG'

export const SET_RADIO_STATION_CHENNEL = 'SET_RADIO_STATION_CHENNEL'

export const SET_VOLUME = 'SET_VOLUME'

export const SET_FAVORITE_SONG_LIST = 'SET_FAVORITE_SONG_LIST'

export const SET_PLAY_SONG_INDEX = 'CHANGE_PLAY_SONG_INDEX'

export const SET_SONG_LIST_TYPE = 'SET_SONG_LIST_TYPE'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_RADIO_STATION_MODE = 'SET_RADIO_STATION_MODE'

export const TOGGLE_PLAYER = 'TOGGLE_PLAYER'

export const TOGGLE_SONG_LIST = 'TOGGLE_SONG_LIST'

export const DELECT_SONG = 'DELECT_SONG'

export const CLEAR_SONG_LIST = 'CLEAR_SONG_LIST'

export const PLAYING = 'PLAYING'

export const SHOW_PLAYER = 'SHOW_PLAYER'

export const NEED_PREV_SONG = 'NEED_PREV_SONG'
